In [1]:
import numpy as np

In [6]:
#Q1)Create a numpy array starting from 2 till 50 with a stepsize of 3.
#CODE-
arr = np.arange(2,51,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


In [12]:
import numpy

In [16]:
#Q2)Accept two lists of 5 elements each from the user.Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.
#CODE-
list1 = []
n1 = int(input("Enter size of list 1st:-"))
print("Enter Any Five Elemets in List 1st:-")
for i in range(0,n1):
    x = int(input())  
    list1.append(x)
list2 = []
n2 = int(input("Enter size of list 2nd:-"))
print("Enter Any Five Elements in list 2nd:-")
for j in range(0,n2):
    y = int(input())
    list2.append(y)

# convert both list to numpy array
print("list converted to numpy arrays:-")
arr1 = numpy.array(list1)
arr2 = numpy.array(list2)
print(arr1)
print(arr2)

# concatenate these two arrays and print it
print("Numpy array After concatenation:-")
print(np.concatenate((arr1,arr2)))

#sort these numpy arrays and print it
print("Numpy arrays after sorting:-")
array1 = np.sort(arr1)
array2 = np.sort(arr2)

print(array1)
print(array2)

    

Enter size of list 1st:-5
Enter Any Five Elemets in List 1st:-
82
4
12
36
75
Enter size of list 2nd:-5
Enter Any Five Elements in list 2nd:-
12
3
1
74
56
list converted to numpy arrays:-
[82  4 12 36 75]
[12  3  1 74 56]
Numpy array After concatenation:-
[82  4 12 36 75 12  3  1 74 56]
Numpy arrays after sorting:-
[ 4 12 36 75 82]
[ 1  3 12 56 74]


In [17]:
#Q3)Write a code snippet to find the dimensions of a ndarray and its size.
#CODE-
import numpy as np
def main():
  print("Dimensions of a 2D numpy array using ndarray.shape ")

  # Create a 2D Numpy array list of list
  arr2D = np.array([[11 ,12,13,11], [21, 22, 23, 24], [31,32,33,34]])
  print('2D Numpy Array')
  print(arr2D)

  # get number of rows in 2D numpy array
  numOfRows = arr2D.shape[0]
  # get number of columns in 2D numpy array
  numOfColumns = arr2D.shape[1]
  print('Number of Rows : ', numOfRows)
  print('Number of Columns : ', numOfColumns)
  print('Total Number of elements in 2D Numpy array : ', arr2D.shape[0] * arr2D.shape[1])
  print("Dimensions of a 1D numpy array using ndarray.shape ")

  # Create a Numpy array from list of numbers
  arr = np.array([4, 5, 6, 7, 8, 9, 10, 11])
  print('Original Array : ', arr)
  print('Shape of 1D numpy array : ', arr.shape)
  print('length of 1D numpy array : ', arr.shape[0])
  print("Dimensions of a 2D numpy array using np.size()")

  # Create a 2D Numpy array list of list
  arr2D = np.array([[11, 12, 13, 11], [21, 22, 23, 24], [31, 32, 33, 34]])
  print('2D Numpy Array')
  print(arr2D)
  # get number of rows in 2D numpy array
  numOfRows = np.size(arr2D, 0)
  # get number of columns in 2D numpy array
  numOfColumns = np.size(arr2D, 1)
  print('Number of Rows : ', numOfRows)
  print('Number of Columns : ', numOfColumns)
  print('Total Number of elements in 2D Numpy array : ', np.size(arr2D))
  print("Dimensions of a 3D numpy array using np.size()")

  # Create a 3D Numpy array list of list of list
  arr3D = np.array([ [[11, 12, 13, 11], [21, 22, 23, 24], [31, 32, 33, 34]],
                   [[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3]] ])
  print('3D Numpy Array')
  print(arr3D)
  print('Axis 0 size : ', np.size(arr3D, 0))
  print('Axis 1 size : ', np.size(arr3D, 1))
  print('Axis 2 size : ', np.size(arr3D, 2))
  print('Total Number of elements in 3D Numpy array : ', np.size(arr3D))
  print('Dimension by axis : ', arr3D.shape)
  print("Dimensions of a 1D numpy array using numpy.size()")

  # Create a Numpy array from list of numbers
  arr = np.array([4, 5, 6, 7, 8, 9, 10, 11])
  print('Original Array : ', arr)
  print('Length of 1D numpy array : ', np.size(arr))
if __name__ == '__main__':
  main()

Dimensions of a 2D numpy array using ndarray.shape 
2D Numpy Array
[[11 12 13 11]
 [21 22 23 24]
 [31 32 33 34]]
Number of Rows :  3
Number of Columns :  4
Total Number of elements in 2D Numpy array :  12
Dimensions of a 1D numpy array using ndarray.shape 
Original Array :  [ 4  5  6  7  8  9 10 11]
Shape of 1D numpy array :  (8,)
length of 1D numpy array :  8
Dimensions of a 2D numpy array using np.size()
2D Numpy Array
[[11 12 13 11]
 [21 22 23 24]
 [31 32 33 34]]
Number of Rows :  3
Number of Columns :  4
Total Number of elements in 2D Numpy array :  12
Dimensions of a 3D numpy array using np.size()
3D Numpy Array
[[[11 12 13 11]
  [21 22 23 24]
  [31 32 33 34]]

 [[ 1  1  1  1]
  [ 2  2  2  2]
  [ 3  3  3  3]]]
Axis 0 size :  2
Axis 1 size :  3
Axis 2 size :  4
Total Number of elements in 3D Numpy array :  24
Dimension by axis :  (2, 3, 4)
Dimensions of a 1D numpy array using numpy.size()
Original Array :  [ 4  5  6  7  8  9 10 11]
Length of 1D numpy array :  8


In [23]:
#Q4)How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
#CODE-
import numpy as np
print("Convert a 1D array into a 2D array:-")
list = []
n = int(input("Enter size of list:-"))
print("Enter Any",n,"Elements:-")
for i in range(0,n):
    ele = int(input())
    list.append(ele)
print("1D array be:-")
array_1D = np.array(list)
print(array_1D)
    
print("Enter any dimension of 2D array in which you want to change 1D array:-")
x = int(input())
y = int(input())
    
#converting 1D array to 2D array
array_2D = np.reshape(array_1D,(x,y))
print("Required 2D array of",x,"rows and ",y,"columns be-")
print(array_2D)


Convert a 1D array into a 2D array:-
Enter size of list:-9
Enter Any 9 Elements:-
1
2
3
4
5
6
7
8
9
1D array be:-
[1 2 3 4 5 6 7 8 9]
Enter any dimension of 2D array in which you want to change 1D array:-
3
3
Required 2D array of 3 rows and  3 columns be-
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [32]:
#Q5)Consider two square numpy arrays. Stack them vertically and horizontally.
#CODE-
import numpy as np

print("Given two square numpy are be:-")
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2 = np.array([[82,90,7],[890,234,8],[23,89,56]])
print(array1)
print(array2)

a1 = np.vstack((array1, array2))
print("stack both array vertically:-")
print(a1)

print("stack both array horizontally:-")
a2 = np.hstack((array1, array2))
print(a2)
    

Given two square numpy are be:-
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 82  90   7]
 [890 234   8]
 [ 23  89  56]]
stack both array vertically:-
[[  1   2   3]
 [  4   5   6]
 [  7   8   9]
 [ 82  90   7]
 [890 234   8]
 [ 23  89  56]]
stack both array horizontally:-
[[  1   2   3  82  90   7]
 [  4   5   6 890 234   8]
 [  7   8   9  23  89  56]]


In [48]:
#Q6)How to get unique items and counts of unique items?
#CODE-
#solving by assuming we have to perform this on different data structure in python
import numpy as np
x = np.array([1, 1, 2,3, 3,4])
print(x)
print("printing the unique Elements in array:-")
k = np.unique(x)
print(k)
print("printing no. of unique items in given array:-",len(np.unique(x)))


[1 1 2 3 3 4]
printing the unique Elements in array:-
[1 2 3 4]
printing no. of unique items in given array:- 4
